export const REPONSE_GET_DEMOGRAPHICS = 'REPONSE_GET_DEMOGRAPHICS';
export const REPONSE_GET_DEMOGRAPHICS_SUCCESS = 'REPONSE_GET_DEMOGRAPHICS_SUCCESS';
export const REPONSE_GET_DEMOGRAPHICS_FAIL = 'REPONSE_GET_DEMOGRAPHICS_FAIL';
